[workspace]
members = [
  "sarif-fmt",
  "hadolint-sarif",
  "shellcheck-sarif",
  "clippy-sarif",
  "clang-tidy-sarif",
  "serde-sarif",
  "miri-sarif",
  "deny-sarif",
]

[profile.release]
strip = true
