[package]
name = "shellcheck-sarif"
version = "0.2.13"
authors = ["Paul Sastrasinh <psastras@gmail.com>"]
edition = "2018"
description = "Convert shellcheck output to SARIF"
license = "MIT"
readme = "README.md"
keywords = ["sarif", "shellcheck", "shell", "cli"]
categories = ["command-line-utilities"]
build = "build.rs"
homepage  = "https://github.com/psastras/sarif-rs"
documentation = "https://psastras.github.io/sarif-rs/shellcheck_sarif/index.html"
repository = "https://github.com/psastras/sarif-rs"

[badges]
github = { repository = "psastras/sarif-rs" }

[[bin]]
name = "shellcheck-sarif"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.33"
serde-sarif = { path = "../serde-sarif", version = "0.2.13", features = ["shellcheck-converters"] }

[dependencies.clap]
version = "3.0.0-beta.2"

[dev-dependencies]
version-sync = "0.9"

[build-dependencies]
cargo-readme = "3.2.0"
