#![doc(html_root_url = "https://docs.rs/miri-sarif/0.7.0")]

//! This crate provides a command line tool to convert `cargo miri` diagnostic
//! output into SARIF.
//!
//! The latest [documentation can be found here](https://docs.rs/miri_sarif).
//!
//! Miri is an undefined behavior detection tool for rust. More information
//! can be found on the official repository: [https://github.com/rust-lang/miri](https://github.com/rust-lang/miri)
//!
//! SARIF or the Static Analysis Results Interchange Format is an industry
//! standard format for the output of static analysis tools. More information
//! can be found on the official website: [https://sarifweb.azurewebsites.net/](https://sarifweb.azurewebsites.net/).
//!
//! ## Installation
//!
//! `miri-sarif` may be installed via `cargo`
//!
//! ```shell
//! cargo install miri-sarif
//! ```
//!
//! or downloaded directly from Github Releases
//!
//! ```shell
//! # make sure to adjust the target and version (you may also want to pin to a specific version)
//! curl -sSL https://github.com/psastras/sarif-rs/releases/download/miri-sarif-v0.7.0/miri-sarif-x86_64-unknown-linux-gnu -o miri-sarif
//! ```
//!
//! ## Usage
//!
//! For miri to output machine readable data you need to pass `--error-format=json` in the `MIRIFLAGS` environment variable.
//!
//! ### `cargo miri test` & `cargo miri run`
//!
//! Because the relevant miri output is printed to stderr you will need to redirect
//! stderr to stdout and stdout to `/dev/null`.
//!
//! #### Example
//!
//! ```shell
//! MIRIFLAGS="--error-format=json" cargo miri test 2>&1 1>/dev/null | miri-sarif
//! ```
//!
//! ### `cargo miri nextest`
//!
//! Since `nextest` only outputs to stderr, you don't need to redirect stdout to `/dev/null`.
//! But you should use `--success-output immediate` to also capture warnings produced by miri.
//! Additionally you can use `--no-fail-fast` for miri to run all tests and not stop on the first failure.
//!
//! #### Example
//!
//! ```shell
//! MIRIFLAGS="--error-format=json" cargo miri nextest --no-fail-fast --success-output immediate 2>&1 | miri-sarif
//! ```
//!
//! ## Github Actions
//!
//! If you are using Github Actions, SARIF is useful for integrating with
//! Github Advanced Security (GHAS), which can show code alerts in the
//! "Security" tab of your repository.
//!
//! After uploading `clippy-sarif` output to Github, `clippy` diagnostics
//! are available in GHAS.
//!
//! ### Example
//!
//! ```yaml
//! on:
//!   workflow_run:
//!     workflows: ["main"]
//!     branches: [main]
//!     types: [completed]
//!
//! name: sarif
//!
//! jobs:
//!   upload-sarif:
//!     runs-on: ubuntu-latest
//!     if: ${{ github.ref == 'refs/heads/main' }}
//!     steps:
//!       - uses: actions/checkout@v2
//!       - uses: actions-rs/toolchain@v1
//!         with:
//!           profile: minimal
//!           toolchain: nightly
//!           components: miri
//!           override: true
//!       - uses: Swatinem/rust-cache@v1
//!       - run: cargo install miri-sarif sarif-fmt cargo-nextest
//!       - run: MIRIFLAGS="--error-format=json" cargo miri nextest run --no-fail-fast --success-output immediate 2>&1 |
//!           miri-sarif | tee results.sarif | sarif-fmt
//!       - name: Upload SARIF file
//!         uses: github/codeql-action/upload-sarif@v3
//!         with:
//!           sarif_file: results.sarif
//! ```

use anyhow::Result;
use clap::Parser;
use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};

#[derive(Parser, Debug)]
#[command(
  version,
  about = "Convert miri output into SARIF",
  after_help = "The expected input is generated by running 'MIRIFLAGS=\"--error-format=json\" cargo miri test'.",
  long_about = None,
)]
struct Args {
  /// input file; reads from stdin if none is given
  #[arg(short, long)]
  input: Option<std::path::PathBuf>,
  /// output file; writes to stdout if none is given
  #[arg(short, long)]
  output: Option<std::path::PathBuf>,
}

fn main() -> Result<()> {
  let args = Args::parse();

  let read = match args.input {
    Some(path) => Box::new(File::open(path)?) as Box<dyn Read>,
    None => Box::new(std::io::stdin()) as Box<dyn Read>,
  };
  let reader = BufReader::new(read);

  let write = match args.output {
    Some(path) => Box::new(File::create(path)?) as Box<dyn Write>,
    None => Box::new(std::io::stdout()) as Box<dyn Write>,
  };
  let writer = BufWriter::new(write);

  serde_sarif::converters::miri::parse_to_writer(reader, writer)
}
