name: auto merge

on: pull_request_target

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        if: github.actor == 'dependabot[bot]' || github.actor == 'psastras'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: "REBASE"
